### ISSUE TITLE
gatk.jar not downloaded with conda create env

### ISSUE THREAD

**Issue by olneykimberly** [SexChrLab/PopInf#1]
gatk-register requires a path to the gatk.jar file but where would that file be at? 

It's not in the miniconda PopInf env:

![Screen Shot 2019-07-10 at 2 46 24 PM](https://user-images.githubusercontent.com/10413269/61007360-7ee9a380-a321-11e9-88f9-884f611215c1.png)

![Screen Shot 2019-07-10 at 2 42 51 PM](https://user-images.githubusercontent.com/10413269/61007324-637e9880-a321-11e9-966c-4475466f951a.png)

**Comment by angelat1020** [comment]
The readme has been updated with directions on how to download the GATK jar file from the Broad Institute. Once the jar file is downloaded, it can be registered and used using conda.
